# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  code-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
       mvn -B package --file pom.xml
       echo 【The war package as below:】
       ls -l ./target/
    - uses: actions/upload-artifact@v2
      with:
        name: package
        path: ./target/hello-world.war
#docker image build 
  docker-build:
      runs-on: ubuntu-latest
      needs: code-build
      steps:
        - uses: actions/download-artifact@v2
          with:
            name: package
        - name: docker-build
          run: |
            docker build -t helloworld-maven:v1 .
            docker images
#            docker push silence7788/helloworld-maven:v1
